window.__shard("s17","General Knowledge","Definition",[
{"id":9001,"t":"text","q":"What is Bangladesh?","ans":["a country","country","a country in south asia","south asian country"],"e":"Bangladesh is a country in South Asia."},
{"id":9002,"t":"text","q":"What is the capital of Bangladesh?","ans":["Dhaka","dhaka","dhaka city"],"e":"Dhaka is the capital of Bangladesh."},
{"id":9003,"t":"text","q":"What is the national language of Bangladesh?","ans":["Bangla","Bengali","বাংলা"],"e":"Bangla is the national language of Bangladesh."},
{"id":9004,"t":"text","q":"What is the national flower of Bangladesh?","ans":["water lily","waterlily","shapla","শাপলা"],"e":"The water lily, locally called Shapla, is the national flower of Bangladesh."},
{"id":9005,"t":"text","q":"What is the national bird of Bangladesh?","ans":["doyel","oriental magpie robin","magpie robin","দোয়েল"],"e":"The Oriental magpie-robin, commonly called Doyel, is the national bird of Bangladesh."},
{"id":9006,"t":"text","q":"What is the national animal of Bangladesh?","ans":["royal bengal tiger","bengal tiger","tiger"],"e":"The Royal Bengal tiger is the national animal of Bangladesh."},
{"id":9007,"t":"text","q":"What is the national fruit of Bangladesh?","ans":["jackfruit","কাঁঠাল"],"e":"Jackfruit is the national fruit of Bangladesh."},
{"id":9008,"t":"text","q":"What is the national tree of Bangladesh?","ans":["mango tree","mango","আমগাছ"],"e":"The mango tree is the national tree of Bangladesh."},
{"id":9009,"t":"text","q":"What is the currency of Bangladesh?","ans":["taka","bangladeshi taka","৳"],"e":"The official currency of Bangladesh is the taka."},
{"id":9010,"t":"text","q":"What is the largest mangrove forest in the world?","ans":["sundarbans","the sundarbans"],"e":"The Sundarbans is the world's largest contiguous mangrove forest."},

{"id":9011,"t":"text","q":"What is the largest ocean on Earth?","ans":["pacific ocean","pacific","the pacific ocean"],"e":"The Pacific Ocean is the largest ocean on Earth."},
{"id":9012,"t":"text","q":"What is the largest continent?","ans":["asia"],"e":"Asia is the largest continent by area."},
{"id":9013,"t":"text","q":"What is the smallest continent?","ans":["australia"],"e":"Australia is the smallest continent by area."},
{"id":9014,"t":"text","q":"What is the largest country by area?","ans":["russia"],"e":"Russia is the largest country in the world by area."},
{"id":9015,"t":"text","q":"What is the smallest country in the world?","ans":["vatican city","vatican"],"e":"Vatican City is the world's smallest sovereign state by area."},
{"id":9016,"t":"text","q":"What is the highest mountain above sea level?","ans":["mount everest","everest"],"e":"Mount Everest has the highest elevation above sea level."},
{"id":9017,"t":"text","q":"What is the largest planet in the Solar System?","ans":["jupiter"],"e":"Jupiter is the largest planet in the Solar System."},
{"id":9018,"t":"text","q":"What is the smallest planet in the Solar System?","ans":["mercury"],"e":"Mercury is the smallest planet in the Solar System."},
{"id":9019,"t":"text","q":"What is the closest planet to the Sun?","ans":["mercury"],"e":"Mercury is the planet closest to the Sun."},
{"id":9020,"t":"text","q":"What is Earth's natural satellite?","ans":["moon","the moon"],"e":"The Moon is Earth's natural satellite."},

{"id":9021,"t":"text","q":"What is the star at the center of our Solar System?","ans":["sun","the sun"],"e":"The Sun is the star at the center of our Solar System."},
{"id":9022,"t":"text","q":"What is the red planet?","ans":["mars"],"e":"Mars is commonly called the Red Planet."},
{"id":9023,"t":"text","q":"What is the blue planet?","ans":["earth","the earth"],"e":"Earth is often called the Blue Planet because of its abundant surface water."},
{"id":9024,"t":"text","q":"What is the hottest planet in the Solar System?","ans":["venus"],"e":"Venus has the highest average surface temperature of the planets."},
{"id":9025,"t":"text","q":"What is the largest mammal?","ans":["blue whale"],"e":"The blue whale is the largest known mammal."},
{"id":9026,"t":"text","q":"What is the fastest land animal?","ans":["cheetah","the cheetah"],"e":"The cheetah is the fastest land animal."},
{"id":9027,"t":"text","q":"What is the largest land animal?","ans":["african elephant","elephant"],"e":"The African elephant is the largest living land animal."},
{"id":9028,"t":"text","q":"What is a noun?","ans":["a naming word","naming word","word that names a person place or thing"],"e":"A noun is a word that names a person, place, thing, or idea."},
{"id":9029,"t":"text","q":"What is a verb?","ans":["an action word","action word","word showing action"],"e":"A verb expresses an action, occurrence, or state of being."},
{"id":9030,"t":"text","q":"What is an adjective?","ans":["a describing word","describing word","word that describes"],"e":"An adjective describes or modifies a noun or pronoun."},

{"id":9031,"t":"text","q":"What is a pronoun?","ans":["a word used instead of a noun","word used instead of noun"],"e":"A pronoun is a word used in place of a noun."},
{"id":9032,"t":"text","q":"What is an adverb?","ans":["a word that modifies a verb","modifying word","word that describes an action"],"e":"An adverb commonly modifies a verb, adjective, or another adverb."},
{"id":9033,"t":"text","q":"What is a sentence?","ans":["a group of words expressing a complete thought","complete thought"],"e":"A sentence is a group of words that expresses a complete thought."},
{"id":9034,"t":"text","q":"What is a synonym?","ans":["a word with similar meaning","similar meaning word"],"e":"A synonym is a word that has the same or a similar meaning as another word."},
{"id":9035,"t":"text","q":"What is an antonym?","ans":["a word with opposite meaning","opposite meaning word"],"e":"An antonym is a word with an opposite meaning."},
{"id":9036,"t":"text","q":"What is a dictionary?","ans":["a book of words and meanings","word reference book"],"e":"A dictionary provides information about words and their meanings."},
{"id":9037,"t":"text","q":"What is grammar?","ans":["rules of a language","language rules"],"e":"Grammar is the system of rules governing the structure of a language."},
{"id":9038,"t":"text","q":"What is mathematics?","ans":["study of numbers shapes and patterns","study of numbers"],"e":"Mathematics is the study of numbers, quantities, structures, shapes, and patterns."},
{"id":9039,"t":"text","q":"What is geometry?","ans":["study of shapes and space","study of shapes"],"e":"Geometry is the branch of mathematics concerned with shapes, sizes, and space."},
{"id":9040,"t":"text","q":"What is algebra?","ans":["branch of mathematics using symbols","mathematics using symbols"],"e":"Algebra uses symbols and letters to represent numbers and quantities."},

{"id":9041,"t":"text","q":"What is physics?","ans":["study of matter energy and forces","study of matter and energy"],"e":"Physics studies matter, energy, motion, forces, and their interactions."},
{"id":9042,"t":"text","q":"What is chemistry?","ans":["study of matter and its changes","study of matter"],"e":"Chemistry is the study of matter, its properties, composition, and changes."},
{"id":9043,"t":"text","q":"What is biology?","ans":["study of living organisms","study of life"],"e":"Biology is the scientific study of living organisms."},
{"id":9044,"t":"text","q":"What is botany?","ans":["study of plants","plant science"],"e":"Botany is the branch of biology that studies plants."},
{"id":9045,"t":"text","q":"What is zoology?","ans":["study of animals","animal science"],"e":"Zoology is the branch of biology that studies animals."},
{"id":9046,"t":"text","q":"What is astronomy?","ans":["study of celestial objects","study of space"],"e":"Astronomy is the scientific study of celestial objects and the universe."},
{"id":9047,"t":"text","q":"What is geology?","ans":["study of earth","study of the earth"],"e":"Geology is the scientific study of Earth, its materials, structure, and history."},
{"id":9048,"t":"text","q":"What is geography?","ans":["study of earth places and features","study of earth"],"e":"Geography studies Earth's places, environments, and physical and human features."},
{"id":9049,"t":"text","q":"What is economics?","ans":["study of production distribution and consumption","study of economy"],"e":"Economics studies how resources are produced, distributed, and consumed."},
{"id":9050,"t":"text","q":"What is history?","ans":["study of past events","study of the past"],"e":"History is the study of past events and human societies."},

{"id":9051,"t":"text","q":"What is democracy?","ans":["government by the people","rule by the people"],"e":"Democracy is a system of government in which people participate in governing, commonly through elected representatives."},
{"id":9052,"t":"text","q":"What is a constitution?","ans":["fundamental law of a state","basic law of a country"],"e":"A constitution is the fundamental legal framework of a state."},
{"id":9053,"t":"text","q":"What is citizenship?","ans":["legal membership of a state","membership of a country"],"e":"Citizenship is the legal status of being a member of a state."},
{"id":9054,"t":"text","q":"What is a parliament?","ans":["legislative body","law making body"],"e":"A parliament is a legislative body responsible for making and discussing laws."}])